name: Docker

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

env:
  REGISTRY: swr.cn-south-1.myhuaweicloud.com
  HW_SWR_REGISTRY_USER: "${{ secrets.HW_SWR_REGISTRY_USER }}"
  HW_SWR_REGISTRY_PASSWORD: "${{ secrets.HW_SWR_REGISTRY_PASSWORD }}"
  MM_NOTIFY_URL: "${{ secrets.MM_NOTIFY_URL }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and push image to HW Cloud SWR
      run: |
        docker login -u $HW_SWR_REGISTRY_USER -p $HW_SWR_REGISTRY_PASSWORD $REGISTRY
        sh pull.sh
        data=`cat images.txt`

        if [ $MM_NOTIFY_URL ];then
          curl  -H 'Content-Type: application/json' \
            -d "{\"msgtype\": \"text\",\"text\": {\"content\":\"同步成功 $data \"}}" \
            $MM_NOTIFY_URL
        else
          echo 'MM_NOTIFY_URL not set'
        fi
